/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parking;

import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author LlunaSeguradoPeris
 */
public class ParkingMenu extends javax.swing.JFrame {

    private ParkingManager parkingManager;

    /**
     * Creates new form ParkingMenu
     */
    public ParkingMenu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        parkingManager = new ParkingManager();

    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonResidentVehicle = new javax.swing.JButton();
        jButtonResidentPayments = new javax.swing.JButton();
        jButtonRegisterExit = new javax.swing.JButton();
        jButtonOfficalVehicle = new javax.swing.JButton();
        jButtonRegisterEntry = new javax.swing.JButton();
        jButtonMonthStarts = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonRegisterExit1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.activeCaption);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setForeground(java.awt.SystemColor.activeCaption);
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setFont(new java.awt.Font("Arial Nova", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PARKING MANAGER");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel1.add(jLabel1, gridBagConstraints);

        jButtonResidentVehicle.setBackground(new java.awt.Color(204, 204, 204));
        jButtonResidentVehicle.setFont(new java.awt.Font("Arial Nova", 1, 22)); // NOI18N
        jButtonResidentVehicle.setForeground(new java.awt.Color(102, 102, 102));
        jButtonResidentVehicle.setText("Register Resident Vehicle");
        jButtonResidentVehicle.setActionCommand("Register Entry");
        jButtonResidentVehicle.setAlignmentY(0.0F);
        jButtonResidentVehicle.setAutoscrolls(true);
        jButtonResidentVehicle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jButtonResidentVehicle.setPreferredSize(new java.awt.Dimension(300, 50));
        jButtonResidentVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResidentVehicleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel1.add(jButtonResidentVehicle, gridBagConstraints);

        jButtonResidentPayments.setBackground(new java.awt.Color(204, 204, 204));
        jButtonResidentPayments.setFont(new java.awt.Font("Arial Nova", 1, 22)); // NOI18N
        jButtonResidentPayments.setForeground(new java.awt.Color(102, 102, 102));
        jButtonResidentPayments.setText("Resident Payments");
        jButtonResidentPayments.setAlignmentY(0.0F);
        jButtonResidentPayments.setAutoscrolls(true);
        jButtonResidentPayments.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jButtonResidentPayments.setPreferredSize(new java.awt.Dimension(230, 50));
        jButtonResidentPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResidentPaymentsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 0.3;
        jPanel1.add(jButtonResidentPayments, gridBagConstraints);

        jButtonRegisterExit.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRegisterExit.setFont(new java.awt.Font("Arial Nova", 1, 22)); // NOI18N
        jButtonRegisterExit.setForeground(new java.awt.Color(102, 102, 102));
        jButtonRegisterExit.setText("Register Exit");
        jButtonRegisterExit.setActionCommand("Register Entry");
        jButtonRegisterExit.setAlignmentY(0.0F);
        jButtonRegisterExit.setAutoscrolls(true);
        jButtonRegisterExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jButtonRegisterExit.setPreferredSize(new java.awt.Dimension(200, 50));
        jButtonRegisterExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 0.3;
        jPanel1.add(jButtonRegisterExit, gridBagConstraints);

        jButtonOfficalVehicle.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOfficalVehicle.setFont(new java.awt.Font("Arial Nova", 1, 22)); // NOI18N
        jButtonOfficalVehicle.setForeground(new java.awt.Color(102, 102, 102));
        jButtonOfficalVehicle.setText("Register Official Vehicle");
        jButtonOfficalVehicle.setActionCommand("Register Entry");
        jButtonOfficalVehicle.setAlignmentY(0.0F);
        jButtonOfficalVehicle.setAutoscrolls(true);
        jButtonOfficalVehicle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jButtonOfficalVehicle.setPreferredSize(new java.awt.Dimension(300, 50));
        jButtonOfficalVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOfficalVehicleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 0.3;
        jPanel1.add(jButtonOfficalVehicle, gridBagConstraints);

        jButtonRegisterEntry.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRegisterEntry.setFont(new java.awt.Font("Arial Nova", 1, 22)); // NOI18N
        jButtonRegisterEntry.setForeground(new java.awt.Color(102, 102, 102));
        jButtonRegisterEntry.setActionCommand("Register Entry");
        jButtonRegisterEntry.setAlignmentY(0.0F);
        jButtonRegisterEntry.setAutoscrolls(true);
        jButtonRegisterEntry.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jButtonRegisterEntry.setLabel("Register Entry");
        jButtonRegisterEntry.setPreferredSize(new java.awt.Dimension(200, 50));
        jButtonRegisterEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterEntryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 0.3;
        jPanel1.add(jButtonRegisterEntry, gridBagConstraints);

        jButtonMonthStarts.setBackground(new java.awt.Color(204, 204, 204));
        jButtonMonthStarts.setFont(new java.awt.Font("Arial Nova", 1, 22)); // NOI18N
        jButtonMonthStarts.setForeground(new java.awt.Color(102, 102, 102));
        jButtonMonthStarts.setText("Month Starts");
        jButtonMonthStarts.setActionCommand("Register Entry");
        jButtonMonthStarts.setAlignmentY(0.0F);
        jButtonMonthStarts.setAutoscrolls(true);
        jButtonMonthStarts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jButtonMonthStarts.setPreferredSize(new java.awt.Dimension(230, 50));
        jButtonMonthStarts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMonthStartsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 0.3;
        jPanel1.add(jButtonMonthStarts, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registro-en-linea (2).png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pago-seguro.png"))); // NOI18N
        jLabel3.setMinimumSize(new java.awt.Dimension(128, 120));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coche-de-policia.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lista-de-verificacion_1.png"))); // NOI18N
        jLabel5.setMinimumSize(new java.awt.Dimension(128, 120));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendario.png"))); // NOI18N
        jLabel6.setMinimumSize(new java.awt.Dimension(128, 120));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coche.png"))); // NOI18N
        jLabel7.setMinimumSize(new java.awt.Dimension(128, 120));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(jLabel7, gridBagConstraints);

        jButtonRegisterExit1.setBackground(new java.awt.Color(174, 174, 174));
        jButtonRegisterExit1.setFont(new java.awt.Font("Arial Nova", 1, 22)); // NOI18N
        jButtonRegisterExit1.setForeground(new java.awt.Color(69, 69, 69));
        jButtonRegisterExit1.setText("Exit");
        jButtonRegisterExit1.setActionCommand("Register Entry");
        jButtonRegisterExit1.setAlignmentY(0.0F);
        jButtonRegisterExit1.setAutoscrolls(true);
        jButtonRegisterExit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jButtonRegisterExit1.setMaximumSize(new java.awt.Dimension(20, 20));
        jButtonRegisterExit1.setMinimumSize(new java.awt.Dimension(20, 20));
        jButtonRegisterExit1.setPreferredSize(new java.awt.Dimension(100, 40));
        jButtonRegisterExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterExit1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel1.add(jButtonRegisterExit1, gridBagConstraints);

        jMenuBar1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.hoverBorderColor"));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFocusable(false);
        jMenuBar1.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(168, 30));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(168, 30));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(168, 28));

        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenu1.setMaximumSize(new java.awt.Dimension(48, 24));
        jMenuBar1.add(jMenu1);

        jMenu3.setText("About");
        jMenu3.setFont(new java.awt.Font("Arial Nova", 0, 14)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResidentVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResidentVehicleActionPerformed
        ResidentVehicleDialog dialog = new ResidentVehicleDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonResidentVehicleActionPerformed

    private void jButtonResidentPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResidentPaymentsActionPerformed
        ResidentPaymentsDialog paymentsDialog = new ResidentPaymentsDialog(this, true);
        paymentsDialog.setVisible(true);
        
    }//GEN-LAST:event_jButtonResidentPaymentsActionPerformed

    private void jButtonRegisterExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterExitActionPerformed
        RegisterExitDialog exitDialog = new RegisterExitDialog(this, true);
        exitDialog.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterExitActionPerformed

    private void jButtonOfficalVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOfficalVehicleActionPerformed
        OfficialVehicleDialog offcialDialog = new OfficialVehicleDialog(this, true);
        offcialDialog.setVisible(true);
    }//GEN-LAST:event_jButtonOfficalVehicleActionPerformed

    private void jButtonRegisterEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterEntryActionPerformed
        RegisterEntryDialog entryDialog = new RegisterEntryDialog(this, true);
        entryDialog.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterEntryActionPerformed

    private void jButtonMonthStartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMonthStartsActionPerformed
        MonthStartsDialog newMonthDialog = new MonthStartsDialog(this, true);
        newMonthDialog.setVisible(true);
    }//GEN-LAST:event_jButtonMonthStartsActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
       
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
         String message = "Parking Application \n\n"
                + "This application manages parking vehicles including official vehicles,\n"
                + "resident vehicles, and non-resident entries.\n";

        JOptionPane.showMessageDialog(null, message, "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jButtonRegisterExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterExit1ActionPerformed
        try {
        // Guardar todos los datos relevantes
        parkingManager.exit();
        JOptionPane.showMessageDialog(null, "Todos los datos han sido guardados correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(null, "Error al guardar los datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    // Cerrar la aplicación
    System.exit(0);
    }//GEN-LAST:event_jButtonRegisterExit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkingMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMonthStarts;
    private javax.swing.JButton jButtonOfficalVehicle;
    private javax.swing.JButton jButtonRegisterEntry;
    private javax.swing.JButton jButtonRegisterExit;
    private javax.swing.JButton jButtonRegisterExit1;
    private javax.swing.JButton jButtonResidentPayments;
    private javax.swing.JButton jButtonResidentVehicle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
